{
  inputs,
  config,
  pkgs,
  ...
}:
{
  meadow.style.wallpaper = "${inputs.self}/home/shared/walls/${config.meadow.style.theme}.jpg";

  home = {
    username = "gwen";
    homeDirectory = "/home/gwen";
    stateVersion = "24.11";

    packages = with pkgs; [
      inputs.zen-browser.packages.${system}.default

      asciinema_3
      bemoji
      betterdiscordctl
      bitwarden
      bore-cli
      bruno
      charm
      charm-freeze
      chromium
      circumflex
      clipse
      colordiff
      deadnix
      delta
      docker-compose
      doggo
      eza
      fd
      feh
      fx
      fzf
      gcc
      gh
      git-absorb
      gitmoji-cli
      glab
      glow
      gnumake
      go
      gping
      grimblast
      gum
      helmfile
      httpie
      imagemagick
      inotify-tools
      jq
      jqp
      just
      k9s
      keybase
      kubecolor
      kubectl
      kubectx
      kubernetes-helm
      light
      magic-wormhole
      mods
      nemo
      networkmanagerapplet
      nh
      nix-fast-build
      nix-inspect
      nix-output-monitor
      nix-update
      nixfmt-rfc-style
      obsidian
      onefetch
      openssl
      openvpn
      opkssh
      pavucontrol
      pfetch
      pgcli
      pinentry
      playerctl
      pre-commit
      presenterm
      python311Packages.gst-python
      python311Packages.pip
      python311Packages.pygobject3
      python311Packages.setuptools
      python311Packages.virtualenv
      qutebrowser
      rustup
      satty
      slides
      sops
      starship
      stern
      syncthing
      teams-for-linux
      telegram-desktop
      television
      nix-search-tv
      tldr
      update-nix-fetchgit
      vegeta
      vial
      viddy
      wireplumber
      xdotool
      xwayland
    ];
  };
}
