#!/usr/bin/env bash

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/wallpaper/wallpaper
