#!/bin/bash

INTERFACE=$(ip -o -4 route show to default | awk '{print $5}')
cat /sys/class/net/$INTERFACE/operstate

ip monitor link | while read -r line; do
  cat /sys/class/net/$INTERFACE/operstate
done
