{
  inputs,
  config,
  self,
  pkgs,
  ...
}:
{
  meadow.wallpaper = "${self}/home/shared/walls/${config.meadow.theme}.jpg";
  home = {
    username = "gwen";
    homeDirectory = "/home/gwen";
    stateVersion = "24.11";

    packages = with pkgs; [
      inputs.zen-browser.packages.${system}.default

      awscli2
      bemoji
      betterdiscordctl
      bitwarden
      bore-cli
      bruno
      charm
      charm-freeze
      chromium
      circumflex
      clipse
      colordiff
      copyq
      deadnix
      delta
      devenv
      docker-compose
      doggo
      eza
      fd
      feh
      fx
      fzf
      gcc
      gh
      git-absorb
      git-lfs
      gitmoji-cli
      glab
      glow
      gnumake
      go
      gping
      grimblast
      gum
      helmfile
      imagemagick
      inotify-tools
      jaq
      jq
      jqp
      just
      k9s
      keybase
      kubecolor
      kubectl
      kubectx
      kubernetes-helm
      light
      magic-wormhole
      mods
      nemo
      networkmanagerapplet
      nh
      nix-fast-build
      nix-inspect
      nix-output-monitor
      nix-update
      nixfmt-rfc-style
      obsidian
      onefetch
      openssl
      openvpn
      oras
      pavucontrol
      pfetch
      pgcli
      pinentry
      playerctl
      pre-commit
      presenterm
      python311Packages.gst-python
      python311Packages.pip
      python311Packages.pygobject3
      python311Packages.setuptools
      python311Packages.virtualenv
      qutebrowser
      rcon
      rustup
      satty
      sherlock
      siyuan
      skim
      skopeo
      slides
      sops
      starship
      stern
      syncthing
      t-rec
      teams-for-linux
      telegram-desktop
      television
      nix-search-tv
      tldr
      trunk-io
      tuba
      update-nix-fetchgit
      vegeta
      ventoy
      vhs
      viddy
      watershot
      wireplumber
      xdotool
      xwayland
      yarn
      zed-editor
    ];
  };
}
